require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/schema.rb

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

Lint/MissingSuper:
  Enabled: false

RSpec/ExampleLength:
  Max: 20
